# Generated by Django 5.2.4 on 2025-07-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_quiz_delete_createquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
