# Generated by Django 5.2.4 on 2025-07-19 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_prequizanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_image', models.ImageField(upload_to='certificates/templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_drawn', models.CharField(max_length=255)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('generated_image', models.ImageField(upload_to='certificates/generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pre_quiz_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.prequizanswer')),
                ('pre_quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.prequizquestion')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.quiz')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.certificatetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
