# Generated by Django 5.2.4 on 2025-07-22 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_quiz_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('attempt_id', models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('score', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.generatedcertificate')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.quiz')),
            ],
        ),
    ]
