# Generated by Django 5.2.4 on 2025-07-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_prequizanswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prequizanswer',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
