# Generated by Django 5.2.4 on 2025-07-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_prequizanswer_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prequizanswer',
            name='user',
        ),
    ]
