# Generated by Django 5.2.4 on 2025-07-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_prequizanswer_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quiz',
            table='quiz',
        ),
    ]
