# Generated by Django 5.2.4 on 2025-07-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_quiz_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificatetemplate',
            table='certificate_template',
        ),
        migrations.AlterModelTable(
            name='generatedcertificate',
            table='generated_certificate',
        ),
        migrations.AlterModelTable(
            name='prequizanswer',
            table='pre_quiz_answer',
        ),
        migrations.AlterModelTable(
            name='prequizquestion',
            table='pre_quiz_question',
        ),
        migrations.AlterModelTable(
            name='quizattempt',
            table='quiz_attempt',
        ),
        migrations.AlterModelTable(
            name='quizquestion',
            table='quiz_question',
        ),
    ]
