# Generated by Django 5.2.4 on 2025-07-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_alter_certificatetemplate_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailotp',
            table='email_otp_handler',
        ),
        migrations.AlterModelTable(
            name='signup',
            table='user_signup',
        ),
    ]
